#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
##
# Description:-
#
#       Enterprise Conversational Engine module leveraging Google Gemini via
#       Vertex AI and LangChain. Implements multi-turn conversational memory,
#       dynamic persona system instructions, synchronous invocation, and token streaming.
#
##
# Development date    Developed by       Comments
# ----------------    ------------       ---------
# 14/08/2024          Saddam Khan        Initial implementation
# 10/09/2024          Saddam Khan        Enhanced multi-turn memory engine and token streaming
#
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

import os
from typing import Generator, Dict, Any, List
from langchain_google_vertexai import ChatVertexAI
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.chat_history import InMemoryChatMessageHistory, BaseChatMessageHistory
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_core.messages import BaseMessage
from config import settings
from utils.auth import resolve_gcp_project

class GeminiChatbot:
    """
    Explanation: Enterprise Conversational Engine using Gemini via Google Cloud Vertex AI & LangChain.
                 Supports multi-turn memory, customizable personas, and streaming responses.
    """

    def __init__(
        self,
        model_name: str = None,
        project_id: str = None,
        location: str = None,
        temperature: float = None,
        system_instruction: str = None,
    ):
        """
        Explanation: Initializes GeminiChatbot instance with Vertex AI configuration and LangChain chain
        :param  model_name str: Identifier of Gemini foundation model (e.g., gemini-1.5-flash, gemini-1.5-pro)
        :param  project_id str: Google Cloud Platform project identifier
        :param  location str: Target GCP region for Vertex AI endpoints (e.g., us-central1)
        :param  temperature float: Sampling temperature controlling model randomness (0.0 to 1.0)
        :param  system_instruction str: High-level persona and system prompt guidelines for LLM
        :return None: Instantiates conversational engine object
        """
        self.project_id = resolve_gcp_project(project_id or settings.project_id)
        self.location = location or settings.location
        self.model_name = model_name or settings.model_name
        self.temperature = temperature if temperature is not None else settings.temperature
        self.system_instruction = system_instruction or settings.system_instruction

        # In-memory session store: session_id -> InMemoryChatMessageHistory
        self._session_store: Dict[str, InMemoryChatMessageHistory] = {}

        # Initialize LLM
        self.llm = ChatVertexAI(
            model=self.model_name,
            project=self.project_id if self.project_id else None,
            location=self.location,
            temperature=self.temperature,
            max_output_tokens=settings.max_output_tokens,
            max_retries=1,
        )

        # Build Prompt Template with System Persona and History Placeholder
        self.prompt = ChatPromptTemplate.from_messages([
            ("system", self.system_instruction),
            MessagesPlaceholder(variable_name="history"),
            ("human", "{input}"),
        ])

        # Core Chain
        self.chain = self.prompt | self.llm

        # Wrapped Conversational Chain with Message History
        self.conversational_chain = RunnableWithMessageHistory(
            self.chain,
            self._get_session_history,
            input_messages_key="input",
            history_messages_key="history",
        )

    def _get_session_history(self, session_id: str) -> BaseChatMessageHistory:
        """
        Explanation: Retrieves or initializes an in-memory chat message history for a session
        :param  session_id str: Unique identifier representing user session
        :return history BaseChatMessageHistory: LangChain chat message history container
        """
        if session_id not in self._session_store:
            self._session_store[session_id] = InMemoryChatMessageHistory()
        return self._session_store[session_id]

    def chat(self, user_input: str, session_id: str = "default_session") -> str:
        """
        Explanation: Sends a user prompt and returns complete generated text synchronously
        :param  user_input str: Natural language input prompt from user
        :param  session_id str: Conversation session identifier for context memory
        :return response str: Text generated by Gemini model
        """
        response = self.conversational_chain.invoke(
            {"input": user_input},
            config={"configurable": {"session_id": session_id}}
        )
        return response.content

    def stream_chat(self, user_input: str, session_id: str = "default_session") -> Generator[str, None, None]:
        """
        Explanation: Streams response tokens iteratively from Gemini for real-time frontend UI display
        :param  user_input str: Natural language input prompt from user
        :param  session_id str: Conversation session identifier for context memory
        :return chunk Generator[str, None, None]: Stream of string text tokens from Gemini
        """
        for chunk in self.conversational_chain.stream(
            {"input": user_input},
            config={"configurable": {"session_id": session_id}}
        ):
            if chunk.content:
                yield chunk.content

    def get_history(self, session_id: str = "default_session") -> List[BaseMessage]:
        """
        Explanation: Retrieves complete chronological message history for a given session
        :param  session_id str: Conversation session identifier
        :return messages List[BaseMessage]: List of LangChain human and AI messages
        """
        history = self._get_session_history(session_id)
        return history.messages

    def clear_history(self, session_id: str = "default_session") -> None:
        """
        Explanation: Purges conversation history and resets session memory store
        :param  session_id str: Conversation session identifier to clear
        :return None: Empties session history in place
        """
        if session_id in self._session_store:
            self._session_store[session_id].clear()
